### ISSUE TITLE
Add cli utility?

### ISSUE THREAD

**Issue by JaegerP** [danielpetri1/BBB-Whiteboard#6]
Hi Daniel,
I'm planning to use BBB for a conference in which we plan to record the talks. I realized WAY too late that there is no default way to download the videos, so I would like to add a script that allows something like

`bbb-downloader <base_url>`

to download videos. Would that be a useful addition to this project?

**Comment by JaegerP** [comment]
Update: on the BBB server I'm using, the urls of the video files seem to be different 'video/webcams.mp4' and 'deskshare/deskshare.mp4' throw 404s. Any idea?

**Comment by hostbbb** [comment]
By default in 2.2 presentation.yml only creates .webm files in recordings. You can edit and switch this to .mp4

**Comment by danielpetri1** [comment]
Hi @JaegerP ,
That would certainly be a useful addition to this project. I'm going to attempt to add it now.

Note that since you have access to the BBB server, you don't have to download the files: referencing the files directly instead would be much faster and save you a lot of time and space.

**Comment by JaegerP** [comment]
I actually don't have access to the server - now I can download the .webm files, but I haven't figured out how to use them in the script (I don't know a whole lot about ruby, so I haven't tried too too hard).

Our conference goes live later today (as I said, I realized way WAY too late), so we'll have to go with screencast recording. I'd still be interested to push this forward, if I can be of help.

**Comment by danielpetri1** [comment]
Ah, I see!
I added some very basic CLI to hopefully make it easier to use (it is far from complete though), with the usage being explained in the README.

I hope your conference went well regardless, screencast recording currently does seem to be the best option. If your conference is public / does not contain anything private, I can run the script on it for you if you wish.

Thanks for offering help, it is very much appreciated!

**Comment by JaegerP** [comment]
Thanks, I think the conference went pretty well.

We ended up not doing recordings in BBB at all, but I will keep testing. Unless I'm mistaken it should be possible to decode .webm files using ffmpeg as well, so hopefully this can be incorporated in your script. I'll let you know if I make any progress.

Since you've added a CLI, maybe we should close this issue and start a new one on the decoding part?

**Comment by danielpetri1** [comment]
Hi, yes, the idea is to have many different transparent webm files for each one of the layers (e.g. mouse, presentation) to recreate the video. This way the user will be able to customize the output video further.
