### ISSUE TITLE
:85:in `require': cannot load such file -- nokogiri 

### ISSUE THREAD

**Issue by spider-x** [danielpetri1/BBB-Whiteboard#9]
Hello, i'm trying to run your script on windows 10, i have installed ruby with DEVKIT. But it still showing me this error. Can you tell me what to do? And where should i put the ffmpeg and librsvg files? Thank you for help.
`<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- nokogiri (LoadError)
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from presentation-render.rb:1:in `<main>'`

**Comment by danielpetri1** [comment]
Hey, this script isn't tested on windows 10 at all, but it looks like nokogiri isn't installed on your system yet. 

The script will create the necessary folders that will hold the files for ffmpeg. 

Kind regards,
Daniel

**Comment by spider-x** [comment]
The problem solved command :
`ridk exec pacman -S mingw-w64-x86_64-libxslt
gem install nokogiri --platform=ruby -- --use-system-libraries`
