### ISSUE TITLE
BBB v3, can we make it compatible ?

### ISSUE THREAD

**Issue by clementgineste** [danielpetri1/BBB-Whiteboard#92]
Hello there,

Will it work with BBB v3 in the near future?
What changes have broken compatibility with >v2.5? If an adaptation is made for v2.7, will it be compatible with v3?

**Comment by danielpetri1** [comment]
Hi,
The whiteboard started to use Tldraw instead of the legacy one. I have made the necessary changes to the bbb-presentation-video project, feel free to check it out. I believe it's called the "video" format in BBB.

**Comment by clementgineste** [comment]
> Hi, The whiteboard started to use Tldraw instead of the legacy one. I have made the necessary changes to the bbb-presentation-video project, feel free to check it out. I believe it's called the "video" format in BBB.

Hello Daniel,

Thanks for you answer :) 
I'm looking for the chat functionality, to generate a video with the chat to be able to erase classic presentation and export to an external storage.
As i see, there is an unresolved issue on that matter on bbb-presentation-video https://github.com/bigbluebutton/bbb-presentation-video/issues/48

**Comment by danielpetri1** [comment]
Hello,
yes, unfortunately, the chat is not supported yet as you've identified.
